import { SpeedInsights } from '@vercel/speed-insights/next';

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const style = {
	background: 'rgb(41,37,37)',
	color: 'rgba(255,255,255,0.5)',
	padding: '0',
	margin: '0',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body style={style} className={inter.className}>
				{children}
				<SpeedInsights />
			</body>
		</html>
	);
}
